import type { Config } from 'tailwindcss'

export default {
  content: [],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#002447',
        'primary-container': '#1b3a5f',
        'on-primary': '#ffffff',
        'on-primary-container': '#88a4cf',
        'secondary': '#735c00',
        'secondary-container': '#fed65b',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#745c00',
        'tertiary': '#312100',
        'tertiary-container': '#4c3500',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#cf9a25',
        'surface': '#f7f9fb',
        'surface-dim': '#d8dadc',
        'surface-bright': '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'surface-container': '#eceef0',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'surface-variant': '#e0e3e5',
        'surface-tint': '#436087',
        'on-surface': '#191c1e',
        'on-surface-variant': '#43474e',
        'on-background': '#191c1e',
        'background': '#f7f9fb',
        'outline': '#74777f',
        'outline-variant': '#c3c6cf',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        'inverse-primary': '#abc8f5',
        'primary-fixed': '#d4e3ff',
        'primary-fixed-dim': '#abc8f5',
        'on-primary-fixed': '#001c39',
        'on-primary-fixed-variant': '#2a486e',
        'secondary-fixed': '#ffe088',
        'secondary-fixed-dim': '#e9c349',
        'on-secondary-fixed': '#241a00',
        'on-secondary-fixed-variant': '#574500',
        'tertiary-fixed': '#ffdea6',
        'tertiary-fixed-dim': '#f7bd48',
        'on-tertiary-fixed': '#271900',
        'on-tertiary-fixed-variant': '#5d4200',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Newsreader', 'serif'],
        label: ['Inter', 'sans-serif'],
      },
      boxShadow: {
        'ambient': '0 12px 32px rgba(27, 58, 95, 0.06)',
        'ambient-lg': '0 12px 32px rgba(27, 58, 95, 0.12)',
      },
    },
  },
} satisfies Config
